import Head from "next/head";
import HeroSection from "../components/HeroSection";
import TestDataTable from "../components/TestDataTable";
import usePlugin from "../utils/usePlugin";
import TableHeader from "../components/TableHeader";
import { GET_REQ } from "../utils/constants";

export default function Home() {
  usePlugin();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/*<link rel="icon" href="/favicon.ico" />*/}
      </Head>
      <main>
        <HeroSection />
        <div className={"grid justify-items-center gap-2"}>
          <TableHeader requestType={GET_REQ} url={"/v3/c2c/accounts/current"} />
          <TestDataTable />
        </div>
      </main>
    </>
  );
}
